[package]
name = "multistr"
version = "0.2.1"
authors = ["Clar Charr <clar@charr.xyz>"]
repository = "https://github.com/clarcharr/multistr"
documentation = "https://clarcharr.github.io/multistr/multistr/"
description = "Multiple strings stored in the same heap buffer."
readme = "README.md"
license-file = "LICENSE"
exclude = [".gitignore"]

[dependencies]
bow = "0.1"
extra-default = "0.1"
len-trait = { version = "0.2", default-features = false, features = ['collections'] }
push-trait = { version = "0.3", default-features = false, features = ['collections'] }

[dev-dependencies]
clippy = "^0.0"
quickcheck = "0.3"

[features]
inclusive_range = []
