[package]
name = "multistr"
version = "0.1.0"
authors = ["Clar Charr <clar@charr.xyz>"]
repository = "https://github.com/clarcharr/multistr"
documentation = "https://clarcharr.github.io/multistr/multistr/"
description = "Multiple strings stored in the same heap buffer."
readme = "README.md"
license-file = "LICENSE"
exclude = [".gitignore"]

[dev-dependencies]
clippy = "^0.0"
quickcheck = "0.3"
